// ==UserScript==
// @name         Vortix Bypass Helper
// @namespace    https://vortix-bypass.vercel.app
// @version      2.5
// @description  Automatically redirects supported shorteners to Vortix Bypass
// @author       Vortix Bypass
// @icon         https://i.ibb.co/FqLb0CxF/F8-F01-A21-CD9-C-4573-9-CB9-8-B2917-ED039-F.png
// @match        *://mobile.codex.lol/*
// @match        *://*trigon/*
// @match        *://*rekonise.com/*
// @match        *://*linkvertise.com/*
// @match        *://*link-target.net/*
// @match        *://*link-center.net/*
// @match        *://*link-to.net/*
// @match        *://*paster.so/*
// @match        *://*cuttlinks.com/*
// @match        *://*boost.ink/*
// @match        *://*bst.gg/*
// @match        *://*keyguardian.net/*
// @match        *://*keyguardian.org/*
// @match        *://*bstshrt.com/*
// @match        *://*nicuse.com/*
// @match        *://*getkey.xyz/*
// @match        *://bit.do/*
// @match        *://bit.ly/*
// @match        *://*blox-script.com/*
// @match        *://cl.gy/*
// @match        *://*cuty.io/*
// @match        *://*cuttlinks.com/*
// @match        *://*getpolsec.com/*
// @match        *://goo.gl/*
// @match        *://is.gd/*
// @match        *://*ldnesfs.com/*
// @match        *://*link-hub.net/*
// @match        *://*link-unlock.com/*
// @match        *://*link4m.com/*
// @match        *://*link4sub.com/*
// @match        *://*linkunlocker.com/*
// @match        *://*lockr.xyz/*
// @match        *://*mboost.me/*
// @match        *://mediafire.com/*
// @match        *://*overdrivehub.com/*
// @match        *://*paste.drop/*
// @match        *://pastebin.com/*
// @match        *://*pastes.io/*
// @match        *://*quartyz.com/*
// @match        *://rebrand.ly/*
// @match        *://*rentry.org/*
// @match        *://*rinku.pro/*
// @match        *://*rkns.link/*
// @match        *://*shorteners-and-direct.com/*
// @match        *://*shorter.me/*
// @match        *://*socialwolvez.com/*
// @match        *://*sub2get.com/*
// @match        *://*sub4unlock.com/*
// @match        *://*subfinal.com/*
// @match        *://t.co/*
// @match        *://t.ly/*
// @match        *://tiny.cc/*
// @match        *://*tinylink.onl/*
// @match        *://tinyurl.com/*
// @match        *://*tpi.li/*
// @match        *://v.gd/*
// @match        *://*work.ink/*
// @match        *://*ytsubme.com/*
// @match        *://krnl.cat/*
// @match        *://keyrblx.com/*
// @match        *://pandadevelopment.net/*
// @match        *://loot-link.com/*
// @match        *://loot-links.com/*
// @match        *://lootlink.org/*
// @match        *://lootlinks.co/*
// @match        *://lootdest.info/*
// @match        *://lootdest.org/*
// @match        *://lootdest.com/*
// @match        *://links-loot.com/*
// @match        *://linksloot.net/*
// @match        *://auth.platoboost.app/*
// @match        *://auth.platorelay.com/*
// @match        *://junkie.development.de/*
// @updateURL    https://vortix-bypass.vercel.app/meta.js
// @downloadURL  https://raw.githubusercontent.com/john2032-design/Bypass-/refs/heads/main/vortix-bypass.user.js
// @grant        GM_xmlhttpRequest
// @run-at       document-start
// ==/UserScript==
